# Generated by Django 5.0 on 2023-12-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing_user_bids_user_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bids',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='item',
        ),
        migrations.RemoveField(
            model_name='user',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Watchlist',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
