# Generated by Django 5.0 on 2023-12-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Watchlist',
            field=models.ManyToManyField(blank=True, related_name='items', to='auctions.listing'),
        ),
    ]
